version: 2

models:
  - name: daily_sales_summary
    columns:
      - name: sale_date
        tests:
          - not_null
          - unique
      - name: total_revenue
        tests:
          - not_null
          - positive_value
