---
AWSTemplateFormatVersion: "2010-09-09"
Description:  S3 Bucket
Parameters:
  Env:
    Type: String
    AllowedValues:
      - dev
      - prod
    Default: dev
Mappings:
  LambdaFunctionMapping:
    dev:
      FunctionArn: arn:aws:lambda:us-east-1:414416470668:function:kasama-tmp
    prod:
      FunctionArn: arn:aws:lambda:us-east-1:414416470668:function:kasama-tmp-prod
Resources:
  CmKasamaRestrictBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cm-kasama-dev-restrict
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: aws:kms
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:  # 通知設定
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:Put'
            Function: !FindInMap [LambdaFunctionMapping, !Ref Env, FunctionArn]
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: csv_list/kasama_test
                  - Name: suffix
                    Value: .csv
          - Event: 's3:ObjectCreated:Post'
            Function: !Sub 'arn:aws:lambda:us-east-1:${AWS::AccountId}:function:kasama-tmp'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: csv_list/kasama_test
                  - Name: suffix
                    Value: .csv
          - Event: 's3:ObjectCreated:CompleteMultipartUpload'
            Function: !Sub 'arn:aws:lambda:us-east-1:${AWS::AccountId}:function:kasama-tmp'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: csv_list/kasama_test
                  - Name: suffix
                    Value: .csv

  # CmKasamaRestrictBucketPolicy:
  #   Type: "AWS::S3::BucketPolicy"
  #   Properties:
  #     Bucket: !Ref CmKasamaRestrictBucket
  #     PolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Effect: Deny
  #           Principal: '*'
  #           Action: "s3:*"
  #           Resource:
  #             - !Sub 'arn:aws:s3:::${CmKasamaRestrictBucket}'
  #             - !Sub 'arn:aws:s3:::${CmKasamaRestrictBucket}/*'
  #           Condition:
  #             StringNotLike:
  #               'aws:userId': !Join ['', [{'Fn::ImportValue': !Sub 'Restrict-Iam-Role-Id-${Env}'}, ':*']]
  #             StringNotEquals:
  #               "aws:CalledVia":
  #                 - "cloudformation.amazonaws.com"
  #               "aws:PrincipalArn":
  #                 - !Sub arn:aws:iam::${AWS::AccountId}:role/cm-kasama-lambda-${Env}-Role
  #                 - !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/access-analyzer.amazonaws.com/AWSServiceRoleForAccessAnalyzer
  #                 - !Sub arn:aws:iam::414416470668:role/service-role/kasama-tmp-role-wfhpo91f
