CREATE EXTERNAL TABLE cm_kasama_salesforce_dev_db.raw_account (
    id STRING,
    isdeleted BOOLEAN,
    masterrecordid STRING,
    name STRING,  -- noqa: RF04
    type STRING,  -- noqa: RF04
    parentid STRING,
    billingstreet STRING,
    billingcity STRING,
    billingstate STRING,
    billingpostalcode STRING,
    billingcountry STRING,
    billinglatitude DOUBLE,
    billinglongitude DOUBLE,
    billinggeocodeaccuracy STRING,
    billingaddress STRING,
    shippingstreet STRING,
    shippingcity STRING,
    shippingstate STRING,
    shippingpostalcode STRING,
    shippingcountry STRING,
    shippinglatitude DOUBLE,
    shippinglongitude DOUBLE,
    shippinggeocodeaccuracy STRING,
    shippingaddress STRING,
    phone STRING,
    fax STRING,
    accountnumber STRING,
    website STRING,
    photourl STRING,
    sic STRING,
    industry STRING,
    annualrevenue STRING,
    numberofemployees INT,
    ownership STRING,  -- noqa: RF04
    tickersymbol STRING,
    description STRING,
    rating STRING,
    site STRING,
    ownerid STRING,
    createddate TIMESTAMP,
    createdbyid STRING,
    lastmodifieddate TIMESTAMP,
    lastmodifiedbyid STRING,
    systemmodstamp TIMESTAMP,
    lastactivitydate TIMESTAMP,
    lastvieweddate TIMESTAMP,
    lastreferenceddate TIMESTAMP,
    jigsaw STRING,
    jigsawcompanyid STRING,
    cleanstatus STRING,
    accountsource STRING,
    dunsnumber STRING,
    tradestyle STRING,
    naicscode STRING,
    naicsdesc STRING,
    yearstarted STRING,
    sicdesc STRING,
    dandbcompanyid STRING,
    operatinghoursid STRING,
    customerpriority__c STRING,
    sla__c STRING,
    active__c STRING,
    numberoflocations__c DOUBLE,
    upsellopportunity__c STRING,
    slaserialnumber__c STRING,
    slaexpirationdate__c TIMESTAMP
)
PARTITIONED BY (
    year STRING,  -- noqa: RF04
    month STRING,  -- noqa: RF04
    day STRING  -- noqa: RF04
)
STORED AS PARQUET
LOCATION 's3://<your-s3-bucket>/cm-kasama-dev-sf-account-flow/'
TBLPROPERTIES (
    'projection.enabled' = 'true',
    'projection.year.type' = 'date',
    'projection.year.format' = 'yyyy',
    'projection.year.range' = '2024,NOW',
    'projection.month.type' = 'integer',
    'projection.month.range' = '1,12',
    'projection.month.digits' = '2',
    'projection.day.type' = 'integer',
    'projection.day.range' = '1,31',
    'projection.day.digits' = '2',
    'storage.location.template' = 's3://<your-s3-bucket>/cm-kasama-dev-sf-account-flow/${year}/${month}/${day}'
);
