merge into cm_kasama_{env}_sf_test.latest_account as tgt
using (
    select
        active__c,
        billinggeocodeaccuracy,
        customerpriority__c,
        dandbcompanyid,
        dunsnumber,
        jigsaw,
        jigsawcompanyid,
        naicsdesc,
        naicscode,
        numberoflocations__c,
        sla__c,
        slaexpirationdate__c,
        slaserialnumber__c,
        shippinggeocodeaccuracy,
        systemmodstamp,
        upsellopportunity__c,
        website,
        cleanstatus,
        masterrecordid,
        ownership,
        shippingaddress,
        billingaddress,
        createddate,
        createdbyid,
        photourl,
        isdeleted,
        fax,
        id,
        type,
        rating,
        description,
        site,
        phone,
        accountsource,
        name,
        accountnumber,
        tradestyle,
        operatinghoursid,
        shippingcountry,
        billingcountry,
        shippingcity,
        billingcity,
        annualrevenue,
        numberofemployees,
        ownerid,
        lastreferenceddate,
        lastmodifieddate,
        lastmodifiedbyid,
        lastactivitydate,
        lastvieweddate,
        tickersymbol,
        industry,
        sic,
        sicdesc,
        shippingstreet,
        billingstreet,
        shippinglongitude,
        billinglongitude,
        shippinglatitude,
        billinglatitude,
        parentid,
        shippingpostalcode,
        billingpostalcode,
        shippingstate,
        billingstate,
        yearstarted
    from cm_kasama_{env}_sf_test.raw_account
    where year = '{}' and month = '{}' and day = '{}'
) as src
    on tgt.id = src.id
when matched then
    update set
        active__c = src.active__c,
        billinggeocodeaccuracy = src.billinggeocodeaccuracy,
        customerpriority__c = src.customerpriority__c,
        dandbcompanyid = src.dandbcompanyid,
        dunsnumber = src.dunsnumber,
        jigsaw = src.jigsaw,
        jigsawcompanyid = src.jigsawcompanyid,
        naicsdesc = src.naicsdesc,
        naicscode = src.naicscode,
        numberoflocations__c = src.numberoflocations__c,
        sla__c = src.sla__c,
        slaexpirationdate__c = src.slaexpirationdate__c,
        slaserialnumber__c = src.slaserialnumber__c,
        shippinggeocodeaccuracy = src.shippinggeocodeaccuracy,
        systemmodstamp = src.systemmodstamp,
        upsellopportunity__c = src.upsellopportunity__c,
        website = src.website,
        cleanstatus = src.cleanstatus,
        masterrecordid = src.masterrecordid,
        ownership = src.ownership,
        shippingaddress = src.shippingaddress,
        billingaddress = src.billingaddress,
        createddate = src.createddate,
        createdbyid = src.createdbyid,
        photourl = src.photourl,
        isdeleted = src.isdeleted,
        fax = src.fax,
        type = src.type,
        rating = src.rating,
        description = src.description,
        site = src.site,
        phone = src.phone,
        accountsource = src.accountsource,
        name = src.name,
        accountnumber = src.accountnumber,
        tradestyle = src.tradestyle,
        operatinghoursid = src.operatinghoursid,
        shippingcountry = src.shippingcountry,
        billingcountry = src.billingcountry,
        shippingcity = src.shippingcity,
        billingcity = src.billingcity,
        annualrevenue = src.annualrevenue,
        numberofemployees = src.numberofemployees,
        ownerid = src.ownerid,
        lastreferenceddate = src.lastreferenceddate,
        lastmodifieddate = src.lastmodifieddate,
        lastmodifiedbyid = src.lastmodifiedbyid,
        lastactivitydate = src.lastactivitydate,
        lastvieweddate = src.lastvieweddate,
        tickersymbol = src.tickersymbol,
        industry = src.industry,
        sic = src.sic,
        sicdesc = src.sicdesc,
        shippingstreet = src.shippingstreet,
        billingstreet = src.billingstreet,
        shippinglongitude = src.shippinglongitude,
        billinglongitude = src.billinglongitude,
        shippinglatitude = src.shippinglatitude,
        billinglatitude = src.billinglatitude,
        parentid = src.parentid,
        shippingpostalcode = src.shippingpostalcode,
        billingpostalcode = src.billingpostalcode,
        shippingstate = src.shippingstate,
        billingstate = src.billingstate,
        yearstarted = src.yearstarted
when not matched then
    insert (
        active__c,
        billinggeocodeaccuracy,
        customerpriority__c,
        dandbcompanyid,
        dunsnumber,
        jigsaw,
        jigsawcompanyid,
        naicsdesc,
        naicscode,
        numberoflocations__c,
        sla__c,
        slaexpirationdate__c,
        slaserialnumber__c,
        shippinggeocodeaccuracy,
        systemmodstamp,
        upsellopportunity__c,
        website,
        cleanstatus,
        masterrecordid,
        ownership,
        shippingaddress,
        billingaddress,
        createddate,
        createdbyid,
        photourl,
        isdeleted,
        fax,
        id,
        type,
        rating,
        description,
        site,
        phone,
        accountsource,
        name,
        accountnumber,
        tradestyle,
        operatinghoursid,
        shippingcountry,
        billingcountry,
        shippingcity,
        billingcity,
        annualrevenue,
        numberofemployees,
        ownerid,
        lastreferenceddate,
        lastmodifieddate,
        lastmodifiedbyid,
        lastactivitydate,
        lastvieweddate,
        tickersymbol,
        industry,
        sic,
        sicdesc,
        shippingstreet,
        billingstreet,
        shippinglongitude,
        billinglongitude,
        shippinglatitude,
        billinglatitude,
        parentid,
        shippingpostalcode,
        billingpostalcode,
        shippingstate,
        billingstate,
        yearstarted
    ) values (
        src.active__c,
        src.billinggeocodeaccuracy,
        src.customerpriority__c,
        src.dandbcompanyid,
        src.dunsnumber,
        src.jigsaw,
        src.jigsawcompanyid,
        src.naicsdesc,
        src.naicscode,
        src.numberoflocations__c,
        src.sla__c,
        src.slaexpirationdate__c,
        src.slaserialnumber__c,
        src.shippinggeocodeaccuracy,
        src.systemmodstamp,
        src.upsellopportunity__c,
        src.website,
        src.cleanstatus,
        src.masterrecordid,
        src.ownership,
        src.shippingaddress,
        src.billingaddress,
        src.createddate,
        src.createdbyid,
        src.photourl,
        src.isdeleted,
        src.fax,
        src.id,
        src.type,
        src.rating,
        src.description,
        src.site,
        src.phone,
        src.accountsource,
        src.name,
        src.accountnumber,
        src.tradestyle,
        src.operatinghoursid,
        src.shippingcountry,
        src.billingcountry,
        src.shippingcity,
        src.billingcity,
        src.annualrevenue,
        src.numberofemployees,
        src.ownerid,
        src.lastreferenceddate,
        src.lastmodifieddate,
        src.lastmodifiedbyid,
        src.lastactivitydate,
        src.lastvieweddate,
        src.tickersymbol,
        src.industry,
        src.sic,
        src.sicdesc,
        src.shippingstreet,
        src.billingstreet,
        src.shippinglongitude,
        src.billinglongitude,
        src.shippinglatitude,
        src.billinglatitude,
        src.parentid,
        src.shippingpostalcode,
        src.billingpostalcode,
        src.shippingstate,
        src.billingstate,
        src.yearstarted
    )
