AWSTemplateFormatVersion: '2010-09-09'
Description: cm-kasama-infa-vpc, private subnets, route tables, and S3 VPC endpoint

Resources:
  InfaVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.16.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: cm-kasama-infa-vpc

  InfaSubnetPrivate1A:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref InfaVPC
      CidrBlock: 172.16.1.0/24
      AvailabilityZone: ap-northeast-1a
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: cm-kasama-infa-vpc-subnet-private1-ap-northeast-1a

  InfaSubnetPrivate2C:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref InfaVPC
      CidrBlock: 172.16.2.0/24
      AvailabilityZone: ap-northeast-1c
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: cm-kasama-infa-vpc-subnet-private2-ap-northeast-1c

  InfaRouteTablePrivate1A:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref InfaVPC
      Tags:
        - Key: Name
          Value: cm-kasama-infa-vpc-rtb-private1-ap-northeast-1a

  InfaRouteTablePrivate2C:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref InfaVPC
      Tags:
        - Key: Name
          Value: cm-kasama-infa-vpc-rtb-private2-ap-northeast-1c

  InfaSubnetRouteTableAssoc1A:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref InfaSubnetPrivate1A
      RouteTableId: !Ref InfaRouteTablePrivate1A

  InfaSubnetRouteTableAssoc2C:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref InfaSubnetPrivate2C
      RouteTableId: !Ref InfaRouteTablePrivate2C

  InfaVPCEndpointS3:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref InfaVPC
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      RouteTableIds:
        - !Ref InfaRouteTablePrivate1A
        - !Ref InfaRouteTablePrivate2C
      VpcEndpointType: Gateway
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:*"
            Resource: "*"
      Tags:
        - Key: Name
          Value: cm-kasama-infa-vpc-vpce-s3

Outputs:
  InfaVPCId:
    Value: !Ref InfaVPC
    Export:
      Name: cm-kasama-infa-vpc-id

  InfaSubnetPrivate1AId:
    Value: !Ref InfaSubnetPrivate1A
    Export:
      Name: cm-kasama-infa-subnet-private1a-id

  InfaSubnetPrivate2CId:
    Value: !Ref InfaSubnetPrivate2C
    Export:
      Name: cm-kasama-infa-subnet-private2c-id

  InfaRouteTablePrivate1AId:
    Value: !Ref InfaRouteTablePrivate1A
    Export:
      Name: cm-kasama-infa-rtb-private1a-id

  InfaRouteTablePrivate2CId:
    Value: !Ref InfaRouteTablePrivate2C
    Export:
      Name: cm-kasama-infa-rtb-private2c-id

  InfaVPCEndpointS3Id:
    Value: !Ref InfaVPCEndpointS3
    Export:
      Name: cm-kasama-infa-vpce-s3-id
