AWSTemplateFormatVersion: '2010-09-09'
Description: cm-kasama-mysql RDS instance (SecretsManager管理)

Parameters:
  DBUser:
    Type: String
    Default: admin
    Description: The database admin account username

Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: cm-kasama-mysql
      Engine: mysql
      EngineVersion: 8.0.40
      DBInstanceClass: db.t4g.micro
      AllocatedStorage: 20
      StorageType: gp2
      MasterUsername: !Ref DBUser
      ManageMasterUserPassword: true
      VPCSecurityGroups:
        - Fn::ImportValue: cm-kasama-rds-mysql-sg-id
      DBSubnetGroupName:
        Fn::ImportValue: cm-kasama-rds-subnet-group-name
      MultiAZ: false
      PubliclyAccessible: false
      BackupRetentionPeriod: 7
      DeletionProtection: false
      StorageEncrypted: true
      KmsKeyId: arn:aws:kms:ap-northeast-1:672842958462:key/aws/rds
      EnableIAMDatabaseAuthentication: false
      Tags:
        - Key: Name
          Value: cm-kasama-mysql

Outputs:
  RDSInstanceEndpoint:
    Value: !GetAtt RDSInstance.Endpoint.Address
    Description: RDS Endpoint Address
  MasterUserSecretArn:
    Value: !GetAtt RDSInstance.MasterUserSecret.SecretArn
    Description: RDS MasterUser Secret ARN
