CREATE EXTERNAL TABLE cm_kasama_dev_sf_test.raw_account(
  active__c string, 
  billinggeocodeaccuracy string, 
  customerpriority__c string, 
  dandbcompanyid string, 
  dunsnumber string, 
  jigsaw string, 
  jigsawcompanyid string, 
  naicsdesc string, 
  naicscode string, 
  numberoflocations__c double, 
  sla__c string, 
  slaexpirationdate__c timestamp, 
  slaserialnumber__c string, 
  shippinggeocodeaccuracy string, 
  systemmodstamp timestamp, 
  upsellopportunity__c string, 
  website string, 
  cleanstatus string, 
  masterrecordid string, 
  ownership string, 
  shippingaddress string, 
  billingaddress string, 
  createddate timestamp, 
  createdbyid string, 
  photourl string, 
  isdeleted boolean, 
  fax string, 
  id string, 
  type string, 
  rating string, 
  description string, 
  site string, 
  phone string, 
  accountsource string, 
  name string, 
  accountnumber string, 
  tradestyle string, 
  operatinghoursid string, 
  shippingcountry string, 
  billingcountry string, 
  shippingcity string, 
  billingcity string, 
  annualrevenue string, 
  numberofemployees int, 
  ownerid string, 
  lastreferenceddate timestamp, 
  lastmodifieddate timestamp, 
  lastmodifiedbyid string, 
  lastactivitydate date, 
  lastvieweddate timestamp, 
  tickersymbol string, 
  industry string, 
  sic string, 
  sicdesc string, 
  shippingstreet string, 
  billingstreet string, 
  shippinglongitude decimal(18,15), 
  billinglongitude decimal(18,15), 
  shippinglatitude decimal(18,15), 
  billinglatitude decimal(18,15), 
  parentid string, 
  shippingpostalcode string, 
  billingpostalcode string, 
  shippingstate string, 
  billingstate string, 
  yearstarted string
)
PARTITIONED BY (
    year string,
    month string,
    day string
)
STORED AS PARQUET
LOCATION 's3://cm-kasama-sf-test/cm-kasama-dev-sf-account-flow/'
TBLPROPERTIES (
    'projection.enabled' = 'true',
    'projection.year.type' = 'date',
    'projection.year.format' = 'yyyy',
    'projection.year.range' = '2024,NOW+9HOURS',
    'projection.month.type' = 'integer',
    'projection.month.range' = '1,12',
    'projection.day.type' = 'integer',
    'projection.day.range' = '1,31',
    'projection.day.digits' = '2',
    'storage.location.template' = 's3://cm-kasama-sf-test/cm-kasama-dev-sf-account-flow/${year}/${month}/${day}'
);
